type L = { hy: string; ru: string; en: string };

export interface SeedCar {
  slug: string;
  brand: string;
  model: string;
  trim?: string;
  year: number;
  mileage: number;
  mileageUnit?: "MI" | "KM";
  engineVolume: number | null;
  horsepower?: number;
  fuel: "GASOLINE" | "DIESEL" | "HYBRID" | "PLUGIN_HYBRID" | "ELECTRIC";
  transmission: "AUTOMATIC" | "MANUAL" | "CVT" | "ROBOTIC";
  drive: "FWD" | "RWD" | "AWD" | "FOUR_WD";
  bodyType: "SEDAN" | "SUV" | "CROSSOVER" | "HATCHBACK" | "COUPE" | "WAGON" | "PICKUP" | "MINIVAN" | "CONVERTIBLE";
  color: string;
  interior: string;
  vin: string;
  price: number;
  location: string;
  source: string;
  status?: "AVAILABLE" | "RESERVED" | "IN_TRANSIT" | "SOLD";
  featured?: boolean;
  features: string[];
  images: string[];
  summary: L;
  history: { owners: number; accidents: number; titleStatus: string; serviceRecords: number; lotNumber?: string };
  daysAgo: number;
}

export const cars: SeedCar[] = [
  {
    slug: "toyota-camry-se-2022",
    brand: "Toyota",
    model: "Camry",
    trim: "SE Hybrid",
    year: 2022,
    mileage: 64000,
    engineVolume: 2.5,
    horsepower: 208,
    fuel: "HYBRID",
    transmission: "AUTOMATIC",
    drive: "FWD",
    bodyType: "SEDAN",
    color: "Celestial Silver",
    interior: "Black SofTex",
    vin: "4T1G31AK5NU012345",
    price: 24900,
    location: "Gyumri",
    source: "Copart",
    featured: true,
    features: ["Toyota Safety Sense 2.5+", "Apple CarPlay / Android Auto", "Adaptive cruise control", "Blind spot monitor", "LED headlights", "Dual-zone climate"],
    images: ["/images/cars/toyota-camry.jpg"],
    summary: {
      en: "The benchmark hybrid sedan: 5 L/100 km in the city, bulletproof reliability and a sporty SE look.",
      ru: "Эталонный гибридный седан: 5 л/100 км в городе, надёжность и спортивный облик версии SE.",
      hy: "Հիբրիդային սեդանի չափանիշը՝ քաղաքում 5 լ/100 կմ, հուսալիություն և SE տարբերակի սպորտային տեսք։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Rebuilt → Armenian registration", serviceRecords: 9, lotNumber: "54821937" },
    daysAgo: 2,
  },
  {
    slug: "tesla-model-3-long-range-2021",
    brand: "Tesla",
    model: "Model 3",
    trim: "Long Range AWD",
    year: 2021,
    mileage: 41000,
    engineVolume: null,
    horsepower: 346,
    fuel: "ELECTRIC",
    transmission: "AUTOMATIC",
    drive: "AWD",
    bodyType: "SEDAN",
    color: "Pearl White",
    interior: "Black premium",
    vin: "5YJ3E1EB2MF987654",
    price: 27500,
    location: "Yerevan",
    source: "IAAI",
    featured: true,
    features: ["Autopilot", "Glass roof", "Heated seats (front & rear)", "Premium audio", "Over-the-air updates", "Heat pump"],
    images: ["/images/cars/tesla-model-3.jpg", "/images/cars/tesla-model-3-2.jpg"],
    summary: {
      en: "Dual-motor all-wheel drive, ~500 km real range and a heat pump for Armenian winters.",
      ru: "Два мотора, полный привод, ~500 км реального запаса хода и тепловой насос для армянской зимы.",
      hy: "Երկու շարժիչ, լիաքարշ, ~500 կմ իրական վազք և ջերմային պոմպ հայկական ձմռան համար։",
    },
    history: { owners: 1, accidents: 0, titleStatus: "Clean", serviceRecords: 4, lotNumber: "37719204" },
    daysAgo: 5,
  },
  {
    slug: "bmw-540i-xdrive-2020",
    brand: "BMW",
    model: "540i",
    trim: "xDrive M Sport",
    year: 2020,
    mileage: 52000,
    engineVolume: 3.0,
    horsepower: 335,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "AWD",
    bodyType: "SEDAN",
    color: "Mineral White",
    interior: "Cognac Dakota leather",
    vin: "WBAJS7C08LCD11223",
    price: 38900,
    location: "Yerevan",
    source: "Copart",
    featured: true,
    features: ["M Sport package", "Harman Kardon", "Head-up display", "Parking assistant", "Heated steering wheel", "Laser lights"],
    images: ["/images/cars/bmw-540i.jpg"],
    summary: {
      en: "Inline-six, xDrive and M Sport styling — the executive sedan that still loves a mountain road.",
      ru: "Рядная шестёрка, xDrive и M Sport — бизнес-седан, который любит горные дороги.",
      hy: "Շարքային վեցմխոց, xDrive և M Sport ոճ՝ գործնական սեդան, որը սիրում է լեռնային ճանապարհները։",
    },
    history: { owners: 2, accidents: 1, titleStatus: "Salvage → repaired", serviceRecords: 12, lotNumber: "61204458" },
    daysAgo: 9,
  },
  {
    slug: "ford-expedition-limited-2019",
    brand: "Ford",
    model: "Expedition",
    trim: "Limited 4x4",
    year: 2019,
    mileage: 78000,
    engineVolume: 3.5,
    horsepower: 375,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "FOUR_WD",
    bodyType: "SUV",
    color: "Oxford White",
    interior: "Ebony leather",
    vin: "1FMJU2AT4KEA44556",
    price: 36500,
    location: "Gyumri",
    source: "IAAI",
    features: ["8 seats", "Panoramic roof", "B&O audio", "Tow package", "Terrain management", "360° camera"],
    images: ["/images/cars/ford-expedition.jpg"],
    summary: {
      en: "Eight seats, twin-turbo V6 and real 4x4 — for big families and mountain villages alike.",
      ru: "Восемь мест, V6 битурбо и настоящий 4x4 — для больших семей и горных сёл.",
      hy: "Ութ նստատեղ, V6 բիտուրբո և իսկական 4x4՝ մեծ ընտանիքների և լեռնային գյուղերի համար։",
    },
    history: { owners: 2, accidents: 0, titleStatus: "Clean", serviceRecords: 15, lotNumber: "33019876" },
    daysAgo: 12,
  },
  {
    slug: "nissan-altima-sr-2021",
    brand: "Nissan",
    model: "Altima",
    trim: "2.5 SR",
    year: 2021,
    mileage: 46000,
    engineVolume: 2.5,
    horsepower: 188,
    fuel: "GASOLINE",
    transmission: "CVT",
    drive: "FWD",
    bodyType: "SEDAN",
    color: "Deep Blue Pearl",
    interior: "Charcoal cloth",
    vin: "1N4BL4CV6MN334455",
    price: 16900,
    location: "Gyumri",
    source: "Copart",
    features: ["ProPILOT Assist", "Remote start", "Apple CarPlay", "LED lights", "Paddle shifters"],
    images: ["/images/cars/nissan-altima.jpg"],
    summary: {
      en: "Comfortable, economical midsize sedan with ProPILOT driver assistance — a sensible daily driver.",
      ru: "Комфортный и экономичный седан с ассистентом ProPILOT — разумный выбор на каждый день.",
      hy: "Հարմարավետ և խնայող սեդան ProPILOT օգնականով՝ խելամիտ ընտրություն ամեն օրվա համար։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Rebuilt", serviceRecords: 6, lotNumber: "48820019" },
    daysAgo: 3,
  },
  {
    slug: "hyundai-accent-sel-2020",
    brand: "Hyundai",
    model: "Accent",
    trim: "SEL",
    year: 2020,
    mileage: 38000,
    engineVolume: 1.6,
    horsepower: 120,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "FWD",
    bodyType: "SEDAN",
    color: "Absolute Black",
    interior: "Black cloth",
    vin: "3KPC24A61LE112233",
    price: 11400,
    location: "Gyumri",
    source: "IAAI",
    features: ["Rear camera", "Bluetooth", "Apple CarPlay", "Cruise control"],
    images: ["/images/cars/hyundai-accent.jpg"],
    summary: {
      en: "Low running costs and cheap parts — the ideal first car or taxi-ready workhorse.",
      ru: "Низкие расходы и дешёвые запчасти — идеальный первый автомобиль или рабочая лошадка.",
      hy: "Ցածր ծախսեր և մատչելի պահեստամասեր՝ իդեալական առաջին մեքենա կամ աշխատանքային ձի։",
    },
    history: { owners: 1, accidents: 0, titleStatus: "Clean", serviceRecords: 5 },
    daysAgo: 14,
  },
  {
    slug: "mercedes-benz-gle-450-coupe-2021",
    brand: "Mercedes-Benz",
    model: "GLE 450",
    trim: "4MATIC Coupe",
    year: 2021,
    mileage: 33000,
    engineVolume: 3.0,
    horsepower: 362,
    fuel: "HYBRID",
    transmission: "AUTOMATIC",
    drive: "AWD",
    bodyType: "CROSSOVER",
    color: "Polar White",
    interior: "Macchiato Beige",
    vin: "4JGFD5KB1MA556677",
    price: 62900,
    location: "Yerevan",
    source: "Copart",
    status: "RESERVED",
    featured: true,
    features: ["EQ Boost mild hybrid", "Burmester sound", "Air suspension", "MBUX widescreen", "Night package", "Massage seats"],
    images: ["/images/cars/mercedes-gle.jpg"],
    summary: {
      en: "Coupe silhouette, EQ Boost mild-hybrid inline-six and air suspension — luxury with presence.",
      ru: "Силуэт купе, рядная шестёрка с EQ Boost и пневмоподвеска — роскошь с характером.",
      hy: "Կուպեի ուրվագիծ, EQ Boost շարքային վեցմխոց և օդային կախոց՝ շքեղություն բնավորությամբ։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Rebuilt", serviceRecords: 7, lotNumber: "70114452" },
    daysAgo: 20,
  },
  {
    slug: "porsche-panamera-4-2019",
    brand: "Porsche",
    model: "Panamera",
    trim: "4",
    year: 2019,
    mileage: 41000,
    engineVolume: 2.9,
    horsepower: 325,
    fuel: "GASOLINE",
    transmission: "ROBOTIC",
    drive: "AWD",
    bodyType: "SEDAN",
    color: "Jet Black Metallic",
    interior: "Black / Chalk leather",
    vin: "WP0AA2A71KL100200",
    price: 64500,
    location: "Yerevan",
    source: "Copart",
    features: ["Sport Chrono", "PASM", "BOSE surround", "Adaptive cruise", "14-way seats", "LED Matrix"],
    images: ["/images/cars/porsche-panamera.jpg"],
    summary: {
      en: "Four doors, 911 DNA. Sport Chrono and PASM make it as happy on the M1 as on the Sevan road.",
      ru: "Четыре двери, ДНК 911. Sport Chrono и PASM — одинаково хорош на трассе и по дороге на Севан.",
      hy: "Չորս դուռ, 911-ի ԴՆԹ։ Sport Chrono և PASM՝ նույնքան լավ մայրուղում և Սևանի ճանապարհին։",
    },
    history: { owners: 2, accidents: 0, titleStatus: "Clean", serviceRecords: 10, lotNumber: "59938812" },
    daysAgo: 7,
  },
  {
    slug: "bmw-430i-coupe-2019",
    brand: "BMW",
    model: "430i",
    trim: "Coupe",
    year: 2019,
    mileage: 49000,
    engineVolume: 2.0,
    horsepower: 248,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "RWD",
    bodyType: "COUPE",
    color: "Estoril Blue",
    interior: "Black Dakota",
    vin: "WBA4W3C58KAF99001",
    price: 23900,
    location: "Gyumri",
    source: "IAAI",
    features: ["M Sport brakes", "Navigation", "Harman Kardon", "Heated seats", "Adaptive LED"],
    images: ["/images/cars/bmw-430i.jpg"],
    summary: {
      en: "Rear-wheel-drive coupe in Estoril Blue — balanced, efficient and genuinely fun.",
      ru: "Заднеприводное купе цвета Estoril Blue — сбалансированное, экономичное и по-настоящему весёлое.",
      hy: "Հետևի քարշակով կուպե Estoril Blue գույնով՝ հավասարակշռված, խնայող և իսկապես զվարճալի։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Rebuilt", serviceRecords: 8, lotNumber: "42207731" },
    daysAgo: 16,
  },
  {
    slug: "chevrolet-camaro-2ss-2018",
    brand: "Chevrolet",
    model: "Camaro",
    trim: "2SS",
    year: 2018,
    mileage: 36000,
    engineVolume: 6.2,
    horsepower: 455,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "RWD",
    bodyType: "COUPE",
    color: "Hyper Blue",
    interior: "Jet Black leather",
    vin: "1G1FH1R78J0133445",
    price: 33900,
    location: "Yerevan",
    source: "Copart",
    features: ["Magnetic Ride", "Performance exhaust", "Head-up display", "Brembo brakes", "Bose audio"],
    images: ["/images/cars/chevrolet-camaro.jpg", "/images/cars/chevrolet-camaro-2.jpg"],
    summary: {
      en: "455 hp naturally aspirated V8 with Magnetic Ride — pure American muscle, properly sorted.",
      ru: "Атмосферный V8 на 455 л.с. и Magnetic Ride — чистый американский маскл-кар.",
      hy: "455 ձ.ու. մթնոլորտային V8 և Magnetic Ride՝ մաքուր ամերիկյան մասլքար։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Salvage → repaired", serviceRecords: 5, lotNumber: "39912003" },
    daysAgo: 25,
  },
  {
    slug: "nissan-juke-tekna-2021",
    brand: "Nissan",
    model: "Juke",
    trim: "Tekna",
    year: 2021,
    mileage: 29000,
    mileageUnit: "KM",
    engineVolume: 1.0,
    horsepower: 114,
    fuel: "GASOLINE",
    transmission: "ROBOTIC",
    drive: "FWD",
    bodyType: "CROSSOVER",
    color: "Ceramic Grey",
    interior: "Black / grey",
    vin: "SJNFBAF16U2233445",
    price: 17800,
    location: "Gyumri",
    source: "Local",
    features: ["Bose headrest speakers", "ProPILOT", "Around View Monitor", "Keyless entry"],
    images: ["/images/cars/nissan-juke.jpg"],
    summary: {
      en: "Compact city crossover with a frugal 1.0 turbo and a very well-equipped Tekna trim.",
      ru: "Компактный городской кроссовер с экономичным 1.0 турбо и богатой комплектацией Tekna.",
      hy: "Կոմպակտ քաղաքային քրոսովեր՝ խնայող 1.0 տուրբոյով և հարուստ Tekna կոմպլեկտացիայով։",
    },
    history: { owners: 1, accidents: 0, titleStatus: "Clean", serviceRecords: 3 },
    daysAgo: 11,
  },
  {
    slug: "audi-a6-45-tfsi-quattro-2019",
    brand: "Audi",
    model: "A6",
    trim: "45 TFSI quattro",
    year: 2019,
    mileage: 57000,
    engineVolume: 2.0,
    horsepower: 248,
    fuel: "GASOLINE",
    transmission: "ROBOTIC",
    drive: "AWD",
    bodyType: "SEDAN",
    color: "Mythos Black",
    interior: "Black Valcona leather",
    vin: "WAUL2AF20KN077889",
    price: 29900,
    location: "Yerevan",
    source: "IAAI",
    features: ["Virtual Cockpit", "Matrix LED", "MMI Touch", "Bang & Olufsen", "Air ioniser"],
    images: ["/images/cars/audi-a6.jpg"],
    summary: {
      en: "quattro grip and a calm, tech-rich cabin — the understated alternative to the 5 Series.",
      ru: "Хватка quattro и спокойный высокотехнологичный салон — сдержанная альтернатива 5 серии.",
      hy: "quattro-ի կառչողականություն և հանգիստ տեխնոլոգիական սրահ՝ 5 սերիայի զուսպ այլընտրանք։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Rebuilt", serviceRecords: 9, lotNumber: "51109827" },
    daysAgo: 19,
  },
  {
    slug: "mercedes-amg-g-63-2019",
    brand: "Mercedes-AMG",
    model: "G 63",
    year: 2019,
    mileage: 44000,
    engineVolume: 4.0,
    horsepower: 577,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "FOUR_WD",
    bodyType: "SUV",
    color: "Obsidian Black",
    interior: "Black nappa",
    vin: "WDCYC7HJ4KX300111",
    price: 139000,
    location: "Yerevan",
    source: "Copart",
    status: "IN_TRANSIT",
    features: ["3 locking differentials", "Burmester", "Night package", "Multicontour seats", "22\" AMG wheels"],
    images: ["/images/cars/mercedes-g63.jpg"],
    summary: {
      en: "The icon. 577 hp biturbo V8, three locking differentials — currently on its way to Armenia.",
      ru: "Икона. V8 битурбо 577 л.с., три блокировки — сейчас в пути в Армению.",
      hy: "Խորհրդանիշ։ 577 ձ.ու. V8 բիտուրբո, երեք արգելափակում՝ այժմ ճանապարհին է դեպի Հայաստան։",
    },
    history: { owners: 2, accidents: 0, titleStatus: "Clean", serviceRecords: 11, lotNumber: "66201934" },
    daysAgo: 1,
  },
  {
    slug: "volkswagen-golf-gti-2017",
    brand: "Volkswagen",
    model: "Golf",
    trim: "GTI",
    year: 2017,
    mileage: 71000,
    engineVolume: 2.0,
    horsepower: 220,
    fuel: "GASOLINE",
    transmission: "ROBOTIC",
    drive: "FWD",
    bodyType: "HATCHBACK",
    color: "Night Blue",
    interior: "Clark plaid",
    vin: "3VW447AU4HM012345",
    price: 14900,
    location: "Gyumri",
    source: "IAAI",
    features: ["DSG", "Adaptive Chassis Control", "Plaid seats", "Fender audio", "Limited-slip differential"],
    images: ["/images/cars/vw-golf.jpg"],
    summary: {
      en: "The original hot hatch: practical on Monday, playful on Sunday.",
      ru: "Оригинальный хот-хэтч: практичный в понедельник, озорной в воскресенье.",
      hy: "Օրիգինալ հոթ-հեչ՝ գործնական երկուշաբթի, խաղացկուն կիրակի։",
    },
    history: { owners: 2, accidents: 0, titleStatus: "Clean", serviceRecords: 14 },
    daysAgo: 30,
  },
  {
    slug: "ford-mustang-gt-2018",
    brand: "Ford",
    model: "Mustang",
    trim: "GT Premium",
    year: 2018,
    mileage: 42000,
    engineVolume: 5.0,
    horsepower: 460,
    fuel: "GASOLINE",
    transmission: "AUTOMATIC",
    drive: "RWD",
    bodyType: "COUPE",
    color: "Shadow Black",
    interior: "Ebony leather",
    vin: "1FA6P8CF1J5100222",
    price: 29500,
    location: "Yerevan",
    source: "Copart",
    features: ["10-speed automatic", "Active exhaust", "MagneRide", "Digital cluster", "B&O audio"],
    images: ["/images/cars/ford-mustang.jpg", "/images/cars/ford-mustang-2.jpg"],
    summary: {
      en: "Coyote 5.0 V8 with active exhaust — 460 hp and a soundtrack to match.",
      ru: "V8 Coyote 5.0 с активным выхлопом — 460 л.с. и соответствующий саундтрек.",
      hy: "Coyote 5.0 V8 ակտիվ արտանետմամբ՝ 460 ձ.ու. և համապատասխան ձայն։",
    },
    history: { owners: 1, accidents: 1, titleStatus: "Rebuilt", serviceRecords: 6, lotNumber: "45560021" },
    daysAgo: 22,
  },
];

export function describe(c: SeedCar, locale: keyof L): string {
  const s = c.summary[locale];
  const more: L = {
    en: `This ${c.year} ${c.brand} ${c.model} is inspected by our technicians, customs-cleared and registered-ready in Armenia. Full photo set, auction history and service records are available on request. Trade-in and installment options are possible — ask your AutoHunt manager.`,
    ru: `Этот ${c.brand} ${c.model} ${c.year} года проверен нашими техниками, растаможен и готов к регистрации в Армении. Полный фотоотчёт, история аукциона и сервисные записи — по запросу. Возможен трейд-ин и рассрочка — уточняйте у менеджера AutoHunt.`,
    hy: `Այս ${c.year} թ. ${c.brand} ${c.model}-ը ստուգված է մեր տեխնիկների կողմից, մաքսազերծված է և պատրաստ է հաշվառման Հայաստանում։ Լուսանկարների ամբողջական հավաքածուն, աճուրդի պատմությունը և սերվիսային գրառումները՝ ըստ պահանջի։ Հնարավոր է trade-in և ապառիկ՝ մանրամասները AutoHunt մենեջերից։`,
  };
  return `${s}\n\n${more[locale]}`;
}
